### ISSUE TITLE
[FIX]

### ISSUE THREAD

**Issue by xxdesmus** [khoj-ai/khoj#1012]
## Describe the bug
As of today -- Dec 16th -- trying to pull the latest code and start the containers results in a near immedate crash by the database container, and errors in the server container.

## To Reproduce

1. Clone the git repo as of 9:24pm PT on December 16th.
2. Edit docker-compose to add OpenAI, Anthropic, and Gemini API keys. Add Ollama endpoint.
3. Use the cloud prod image -- `ghcr.io/khoj-ai/khoj-cloud:latest`
4. `docker compose up -d` 
5. `docker logs -f khoj-server-1

```
django.db.utils.IntegrityError: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(database_khojapiuser_id_seq, 2200) already exists.

[2024-12-17 05:22:41 +0000] [6] [INFO] Worker exiting (pid: 6)
[2024-12-17 05:22:41 +0000] [1] [ERROR] Worker (pid:6) exited with code 3
[2024-12-17 05:22:41 +0000] [1] [ERROR] Worker (pid:7) was sent SIGTERM!
[2024-12-17 05:22:41 +0000] [1] [ERROR] Shutting down: Master
[2024-12-17 05:22:41 +0000] [1] [ERROR] Reason: Worker failed to boot.
```

6. `khoj-database-1`

```
PostgreSQL init process complete; ready for start up.

2024-12-17 05:21:09.474 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-12-17 05:21:09.476 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-12-17 05:21:09.476 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-12-17 05:21:09.477 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-12-17 05:21:09.481 UTC [61] LOG:  database system was shut down at 2024-12-17 05:21:09 UTC
2024-12-17 05:21:09.485 UTC [1] LOG:  database system is ready to accept connections
2024-12-17 05:21:39.933 UTC [74] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:21:39.933 UTC [74] DETAIL:  Key (relname, relnamespace)=(django_migrations_id_seq, 2200) already exists.
2024-12-17 05:21:39.933 UTC [74] STATEMENT:  CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL)
2024-12-17 05:22:41.186 UTC [91] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:22:41.186 UTC [91] DETAIL:  Key (relname, relnamespace)=(database_khojapiuser_id_seq, 2200) already exists.
2024-12-17 05:22:41.186 UTC [91] STATEMENT:  CREATE TABLE "database_khojapiuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" varchar(50) NOT NULL UNIQUE, "name" varchar(50) NOT NULL, "accessed_at" timestamp with time zone NULL, "user_id" bigint NOT NULL)
2024-12-17 05:22:41.531 UTC [92] LOG:  unexpected EOF on client connection with an open transaction
2024-12-17 05:25:43.207 UTC [144] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:25:43.207 UTC [144] DETAIL:  Key (relname, relnamespace)=(database_clientapplication_id_seq, 2200) already exists.
2024-12-17 05:25:43.207 UTC [144] STATEMENT:  CREATE TABLE "database_clientapplication" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "client_id" varchar(200) NOT NULL, "client_secret" varchar(200) NOT NULL)
2024-12-17 05:25:43.520 UTC [143] LOG:  could not receive data from client: Connection reset by peer
2024-12-17 05:25:43.520 UTC [143] LOG:  unexpected EOF on client connection with an open transaction
```

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux (Alpine)
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]: where do I find this? Looks like this is the lateast container image: https://github.com/khoj-ai/khoj/pkgs/container/khoj-cloud/320554390?tag=latest -- from "6 days ago" -- so roughly December 10th.

**Comment by sabaimran** [comment]
I've pulled `resend` into our default dependencies while I look into this further. This should mitigate some other issues as well with the self-hosted / cloud-hosted issues.

Refer to commit: 3b050a33bb52d3db6010cd4adc3dfdeace760d21.

The docker build is done, so it might be worth giving it a go with using the image `ghcr.io/khoj-ai/khoj:dev`. `latest` tag will be built after the next release (probably tomorrow).

Are you seeing any other server logs at all? Any notes about migrations, or initialization?

I'll debug further in the morning PST.

**Comment by xxdesmus** [comment]
I switched over to `ghcr.io/khoj-ai/khoj:dev` and ran docker compose up -- I get this now:

```
2024-12-17 16:34:07.881366240 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 18, index: 4, mask: {5, 11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
Traceback (most recent call last):
  File "/app/src/khoj/main.py", line 93, in <module>
    from khoj.configure import configure_routes, initialize_server, configure_middleware
  File "/app/src/khoj/configure.py", line 45, in <module>
    from khoj.routers.api_content import configure_content, configure_search
  File "/app/src/khoj/routers/api_content.py", line 41, in <module>
    from khoj.routers.helpers import (
  File "/app/src/khoj/routers/helpers.py", line 101, in <module>
    from khoj.routers.email import is_resend_enabled, send_task_email
  File "/app/src/khoj/routers/email.py", line 28, in <module>
    resend.api_key = RESEND_API_KEY
NameError: name 'resend' is not defined
```

even though I have that defined in the environment variables:
```
cat docker-compose.yml | grep RESEND
      - RESEND_API_KEY=re_XXXXXXXXXXX
 ```

**Comment by xxdesmus** [comment]
I switched back to `ghcr.io/khoj-ai/khoj-cloud:latest` and did `docker compose up` again. Here are some additional logs:

`docker logs -f khoj-server-1`
```
[2024-12-17 17:12:13 +0000] [1] [INFO] Starting gunicorn 22.0.0
[2024-12-17 17:12:13 +0000] [1] [DEBUG] Arbiter booted
[2024-12-17 17:12:13 +0000] [1] [INFO] Listening at: http://0.0.0.0:42110 (1)
[2024-12-17 17:12:13 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-12-17 17:12:13 +0000] [6] [INFO] Booting worker with pid: 6
[2024-12-17 17:12:13 +0000] [7] [INFO] Booting worker with pid: 7
[2024-12-17 17:12:13 +0000] [1] [DEBUG] 2 workers
2024-12-17 17:12:14.823862023 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 11, index: 1, mask: {2, 8, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.827380223 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 12, index: 2, mask: {3, 9, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.831369437 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 13, index: 3, mask: {4, 10, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.835376798 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 14, index: 4, mask: {5, 11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.835409451 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 16, index: 1, mask: {2, 8, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.839399084 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 17, index: 2, mask: {3, 9, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.843466098 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 18, index: 3, mask: {4, 10, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-12-17 17:12:14.846371388 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 19, index: 4, mask: {5, 11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
[2024-12-17 17:12:15 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "database_openaiprocessorconversationconfig" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/khoj/main.py", line 52, in <module>
    call_command("migrate", "--noinput")
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/models.py", line 440, in database_forwards
    schema_editor.alter_db_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 681, in alter_db_table
    self.execute(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 202, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 103, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "database_openaiprocessorconversationconfig" does not exist

[2024-12-17 17:12:15 +0000] [7] [INFO] Worker exiting (pid: 7)
[2024-12-17 17:12:16 +0000] [1] [ERROR] Worker (pid:7) exited with code 3
[2024-12-17 17:12:16 +0000] [1] [ERROR] Worker (pid:6) was sent SIGTERM!
[2024-12-17 17:12:16 +0000] [1] [ERROR] Shutting down: Master
[2024-12-17 17:12:16 +0000] [1] [ERROR] Reason: Worker failed to boot.
```


`docker logs -f khoj-database-1` 

```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2024-12-17 05:21:09.193 UTC [47] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-12-17 05:21:09.197 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-12-17 05:21:09.205 UTC [50] LOG:  database system was shut down at 2024-12-17 05:21:08 UTC
2024-12-17 05:21:09.210 UTC [47] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2024-12-17 05:21:09.341 UTC [47] LOG:  received fast shutdown request
waiting for server to shut down....2024-12-17 05:21:09.342 UTC [47] LOG:  aborting any active transactions
2024-12-17 05:21:09.343 UTC [56] FATAL:  terminating connection due to administrator command
2024-12-17 05:21:09.343 UTC [56] LOG:  could not send data to client: Broken pipe
2024-12-17 05:21:09.346 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
2024-12-17 05:21:09.348 UTC [48] LOG:  shutting down
2024-12-17 05:21:09.350 UTC [48] LOG:  checkpoint starting: shutdown immediate
2024-12-17 05:21:09.359 UTC [48] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.002 s, total=0.012 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
2024-12-17 05:21:09.361 UTC [47] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2024-12-17 05:21:09.474 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-12-17 05:21:09.476 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-12-17 05:21:09.476 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-12-17 05:21:09.477 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-12-17 05:21:09.481 UTC [61] LOG:  database system was shut down at 2024-12-17 05:21:09 UTC
2024-12-17 05:21:09.485 UTC [1] LOG:  database system is ready to accept connections
2024-12-17 05:21:39.933 UTC [74] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:21:39.933 UTC [74] DETAIL:  Key (relname, relnamespace)=(django_migrations_id_seq, 2200) already exists.
2024-12-17 05:21:39.933 UTC [74] STATEMENT:  CREATE TABLE "django_migrations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL)
2024-12-17 05:22:41.186 UTC [91] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:22:41.186 UTC [91] DETAIL:  Key (relname, relnamespace)=(database_khojapiuser_id_seq, 2200) already exists.
2024-12-17 05:22:41.186 UTC [91] STATEMENT:  CREATE TABLE "database_khojapiuser" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" varchar(50) NOT NULL UNIQUE, "name" varchar(50) NOT NULL, "accessed_at" timestamp with time zone NULL, "user_id" bigint NOT NULL)
2024-12-17 05:22:41.531 UTC [92] LOG:  unexpected EOF on client connection with an open transaction
2024-12-17 05:25:43.207 UTC [144] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:25:43.207 UTC [144] DETAIL:  Key (relname, relnamespace)=(database_clientapplication_id_seq, 2200) already exists.
2024-12-17 05:25:43.207 UTC [144] STATEMENT:  CREATE TABLE "database_clientapplication" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "name" varchar(200) NOT NULL, "client_id" varchar(200) NOT NULL, "client_secret" varchar(200) NOT NULL)
2024-12-17 05:25:43.520 UTC [143] LOG:  could not receive data from client: Connection reset by peer
2024-12-17 05:25:43.520 UTC [143] LOG:  unexpected EOF on client connection with an open transaction
2024-12-17 05:26:09.538 UTC [59] LOG:  checkpoint starting: time
2024-12-17 05:26:44.504 UTC [59] LOG:  checkpoint complete: wrote 351 buffers (2.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=34.917 s, sync=0.037 s, total=34.967 s; sync files=311, longest=0.009 s, average=0.001 s; distance=2089 kB, estimate=2089 kB
2024-12-17 05:31:09.605 UTC [59] LOG:  checkpoint starting: time
2024-12-17 05:31:12.453 UTC [59] LOG:  checkpoint complete: wrote 29 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.809 s, sync=0.021 s, total=2.849 s; sync files=6, longest=0.009 s, average=0.004 s; distance=238 kB, estimate=1904 kB
2024-12-17 05:33:49.058 UTC [278] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2024-12-17 05:33:49.058 UTC [278] DETAIL:  Key (relname, relnamespace)=(database_publicconversation_id_seq, 2200) already exists.
2024-12-17 05:33:49.058 UTC [278] STATEMENT:  CREATE TABLE "database_publicconversation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "conversation_log" jsonb NOT NULL, "slug" varchar(200) NULL, "title" varchar(200) NULL, "agent_id" bigint NULL, "source_owner_id" bigint NOT NULL)
2024-12-17 05:33:49.405 UTC [277] LOG:  unexpected EOF on client connection with an open transaction
2024-12-17 05:33:53.890 UTC [280] ERROR:  column "style_color" of relation "database_agent" already exists
2024-12-17 05:33:53.890 UTC [280] STATEMENT:  ALTER TABLE "database_agent" ADD COLUMN "style_color" varchar(200) DEFAULT 'blue' NOT NULL
2024-12-17 05:36:09.532 UTC [59] LOG:  checkpoint starting: time
2024-12-17 05:36:18.703 UTC [59] LOG:  checkpoint complete: wrote 92 buffers (0.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=9.125 s, sync=0.022 s, total=9.171 s; sync files=88, longest=0.009 s, average=0.001 s; distance=539 kB, estimate=1768 kB
2024-12-17 16:36:20.708 UTC [59] LOG:  checkpoint starting: time
2024-12-17 16:36:35.263 UTC [59] LOG:  checkpoint complete: wrote 145 buffers (0.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=14.515 s, sync=0.028 s, total=14.556 s; sync files=115, longest=0.009 s, average=0.001 s; distance=919 kB, estimate=1683 kB
2024-12-17 16:46:20.374 UTC [59] LOG:  checkpoint starting: time
2024-12-17 16:46:21.198 UTC [59] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.804 s, sync=0.009 s, total=0.824 s; sync files=1, longest=0.009 s, average=0.009 s; distance=23 kB, estimate=1517 kB
2024-12-17 17:12:15.764 UTC [11794] ERROR:  relation "database_openaiprocessorconversationconfig" does not exist
2024-12-17 17:12:15.764 UTC [11794] STATEMENT:  ALTER TABLE "database_openaiprocessorconversationconfig" RENAME TO "database_aimodelapi
```

**Comment by xxdesmus** [comment]
Switching over to `ghcr.io/khoj-ai/khoj:pre` did fix things. Thanks! I have Resend working on the `ghcr.io/khoj-ai/khoj:pre` image one I also removed `--anonymous-mode` 

My initial problem started when I was using `ghcr.io/khoj-ai/khoj-cloud:latest` -- I had pulled a fresh version of that image.

**Comment by sabaimran** [comment]
Happy to hear it's working! Did you at any point try building the image yourself from source?

We've done a fresh release! You can now migrate to `ghcr.io/khoj-ai/khoj:latest`.

**Comment by xxdesmus** [comment]
"Happy to hear it's working! Did you at any point try building the image yourself from source?"
>> I did not.  Only using the containers.

**Comment by ArjonBu** [comment]
@sabaimran seems like the prod image still doesn't work. Any plans to fix it? What are the differences between the normal and the prod images?
