### ISSUE TITLE
[Obsidian] Khoj first-run indexing runs out of RAM (MemoryError)

### ISSUE THREAD

**Issue by Mahgozar** [khoj-ai/khoj#195]
I'm on a windows machine with python version 3.10

![image](https://user-images.githubusercontent.com/54596777/228474782-302fcd1d-b2f5-433c-8ca4-dcd746e56fe2.png)

![image](https://user-images.githubusercontent.com/54596777/228474848-72f60e01-012d-49dd-a067-59de494b5684.png)

**Comment by debanjum** [comment]
Hey @Mahgozar, it's unfortunate that you're hitting an issue during the auto-configuration of khoj

Could you share more of the error logs you see? Ideally the errors from files like `api.py`, `main.py` and/or `configure.py`

**Comment by Mahgozar** [comment]
can you tell me how can i get those logs? this is all that its showing to me

**Comment by debanjum** [comment]
> In the same error message, I sent before these are specifically mentioning configure.py and api.py

Ah, yeah that's great. Can you also share more of the error after the configure.py as well?

Also did you try restart the khoj backend app and then re-enable the khoj obsidian plugin to see if the issue persists?

**Comment by debanjum** [comment]
> can you tell me how can i get those logs? this is all that its showing to me

The logs get added to the C:\Users\user\.khoj\khoj.log file

**Comment by Mahgozar** [comment]
it behaves weird when i do that, right now i tried to close it with ctrl+c then it showed me this and then i could search in obsidian but it didn't show me anything right now i hit update button to see if it reindexes but it doesn't show me anything that suggests if its doing that 
![image](https://user-images.githubusercontent.com/54596777/228502013-1ab2bca6-8723-4aed-9502-835204370bc4.png)

**Comment by Mahgozar** [comment]
> C:\Users\user.khoj\

Khoj is not configured.
Configure it via khoj GUI, plugins or by editing C:\Users\user\.khoj\khoj.yml.
No query param (q) passed in API call to initiate search
No query param (q) passed in API call to initiate search
No query param (q) passed in API call to initiate search
No query param (q) passed in API call to initiate search

**Comment by Mahgozar** [comment]
> > In the same error message, I sent before these are specifically mentioning configure.py and api.py
> 
> Ah, yeah that's great. Can you also share more of the error after the configure.py as well?
> 
> Also did you try restart the khoj backend app and then re-enable the khoj obsidian plugin to see if the issue persists?

![image](https://user-images.githubusercontent.com/54596777/228503406-63726013-4c02-48f8-a25d-88c9784ac248.png)

these are the errors after config.py

**Comment by Mahgozar** [comment]
when i tried to close it it was stuck for more than 10 minutes on the waiting for background task to finish message then when I force closed it it showed me the following 
```
[13:53:32] INFO     Finished server process [5028]                                                                                                                      server.py:85
           ERROR    Traceback (most recent call last):                                                                                                                     on.py:132
                      File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 638, in lifespan
                        await receive()
                      File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\uvicorn\lifespan\on.py", line 135, in receive
                        return await self.receive_queue.get()
                      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\asyncio\queues.py", line 159, in get
                        await getter
                    asyncio.exceptions.CancelledError

           ERROR    Exception in ASGI application                                                                                                                    h11_impl.py:369

                    ╭───────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────╮
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\uvicorn\protocols\http\h11_impl.py:366 in run_asgi                              │
                    │                                                                                                                                              │
                    │   363 │   # ASGI exception wrapper                                                                                                           │
                    │   364 │   async def run_asgi(self, app):                                                                                                     │
                    │   365 │   │   try:                                                                                                                           │
                    │ ❱ 366 │   │   │   result = await app(self.scope, self.receive, self.send)                                                                    │
                    │   367 │   │   except BaseException as exc:                                                                                                   │
                    │   368 │   │   │   msg = "Exception in ASGI application\n"                                                                                    │
                    │   369 │   │   │   self.logger.error(msg, exc_info=exc)                                                                                       │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\uvicorn\middleware\proxy_headers.py:75 in __call__                              │
                    │                                                                                                                                              │
                    │   72 │   │   │   │   │   port = 0                                                                                                            │
                    │   73 │   │   │   │   │   scope["client"] = (host, port)  # type: ignore[index]                                                               │
                    │   74 │   │                                                                                                                                   │
                    │ ❱ 75 │   │   return await self.app(scope, receive, send)                                                                                     │
                    │   76                                                                                                                                         │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\fastapi\applications.py:269 in __call__                                         │
                    │                                                                                                                                              │
                    │   266 │   async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:                                                      │
                    │   267 │   │   if self.root_path:                                                                                                             │
                    │   268 │   │   │   scope["root_path"] = self.root_path                                                                                        │
                    │ ❱ 269 │   │   await super().__call__(scope, receive, send)                                                                                   │
                    │   270 │                                                                                                                                      │
                    │   271 │   def add_api_route(                                                                                                                 │
                    │   272 │   │   self,                                                                                                                          │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\applications.py:124 in __call__                                       │
                    │                                                                                                                                              │
                    │   121 │                                                                                                                                      │
                    │   122 │   async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:                                                      │
                    │   123 │   │   scope["app"] = self                                                                                                            │
                    │ ❱ 124 │   │   await self.middleware_stack(scope, receive, send)                                                                              │
                    │   125 │                                                                                                                                      │
                    │   126 │   # The following usages are now discouraged in favour of configuration                                                              │
                    │   127 │   # during Starlette.__init__(...)                                                                                                   │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\middleware\errors.py:162 in __call__                                  │
                    │                                                                                                                                              │
                    │   159 │   │   │   await send(message)                                                                                                        │
                    │   160 │   │                                                                                                                                  │
                    │   161 │   │   try:                                                                                                                           │
                    │ ❱ 162 │   │   │   await self.app(scope, receive, _send)                                                                                      │
                    │   163 │   │   except Exception as exc:                                                                                                       │
                    │   164 │   │   │   request = Request(scope)                                                                                                   │
                    │   165 │   │   │   if self.debug:                                                                                                             │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\exceptions.py:82 in __call__                                          │
                    │                                                                                                                                              │
                    │    79 │   │   │   await send(message)                                                                                                        │
                    │    80 │   │                                                                                                                                  │
                    │    81 │   │   try:                                                                                                                           │
                    │ ❱  82 │   │   │   await self.app(scope, receive, sender)                                                                                     │
                    │    83 │   │   except Exception as exc:                                                                                                       │
                    │    84 │   │   │   handler = None                                                                                                             │
                    │    85                                                                                                                                        │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\fastapi\middleware\asyncexitstack.py:18 in __call__                             │
                    │                                                                                                                                              │
                    │   15 │   │   │   async with AsyncExitStack() as stack:                                                                                       │
                    │   16 │   │   │   │   scope[self.context_name] = stack                                                                                        │
                    │   17 │   │   │   │   try:                                                                                                                    │
                    │ ❱ 18 │   │   │   │   │   await self.app(scope, receive, send)                                                                                │
                    │   19 │   │   │   │   except Exception as e:                                                                                                  │
                    │   20 │   │   │   │   │   dependency_exception = e                                                                                            │
                    │   21 │   │   │   │   │   raise e                                                                                                             │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py:670 in __call__                                            │
                    │                                                                                                                                              │
                    │   667 │   │   │   match, child_scope = route.matches(scope)                                                                                  │
                    │   668 │   │   │   if match == Match.FULL:                                                                                                    │
                    │   669 │   │   │   │   scope.update(child_scope)                                                                                              │
                    │ ❱ 670 │   │   │   │   await route.handle(scope, receive, send)                                                                               │
                    │   671 │   │   │   │   return                                                                                                                 │
                    │   672 │   │   │   elif match == Match.PARTIAL and partial is None:                                                                           │
                    │   673 │   │   │   │   partial = route                                                                                                        │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py:266 in handle                                              │
                    │                                                                                                                                              │
                    │   263 │   │   │   │   )                                                                                                                      │
                    │   264 │   │   │   await response(scope, receive, send)                                                                                       │
                    │   265 │   │   else:                                                                                                                          │
                    │ ❱ 266 │   │   │   await self.app(scope, receive, send)                                                                                       │
                    │   267 │                                                                                                                                      │
                    │   268 │   def __eq__(self, other: typing.Any) -> bool:                                                                                       │
                    │   269 │   │   return (                                                                                                                       │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py:65 in app                                                  │
                    │                                                                                                                                              │
                    │    62 │   async def app(scope: Scope, receive: Receive, send: Send) -> None:                                                                 │
                    │    63 │   │   request = Request(scope, receive=receive, send=send)                                                                           │
                    │    64 │   │   if is_coroutine:                                                                                                               │
                    │ ❱  65 │   │   │   response = await func(request)                                                                                             │
                    │    66 │   │   else:                                                                                                                          │
                    │    67 │   │   │   response = await run_in_threadpool(func, request)                                                                          │
                    │    68 │   │   await response(scope, receive, send)                                                                                           │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\fastapi\routing.py:227 in app                                                   │
                    │                                                                                                                                              │
                    │    224 │   │   if errors:                                                                                                                    │
                    │    225 │   │   │   raise RequestValidationError(errors, body=body)                                                                           │
                    │    226 │   │   else:                                                                                                                         │
                    │ ❱  227 │   │   │   raw_response = await run_endpoint_function(                                                                               │
                    │    228 │   │   │   │   dependant=dependant, values=values, is_coroutine=is_coroutine                                                         │
                    │    229 │   │   │   )                                                                                                                         │
                    │    230                                                                                                                                       │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\fastapi\routing.py:162 in run_endpoint_function                                 │
                    │                                                                                                                                              │
                    │    159 │   if is_coroutine:                                                                                                                  │
                    │    160 │   │   return await dependant.call(**values)                                                                                         │
                    │    161 │   else:                                                                                                                             │
                    │ ❱  162 │   │   return await run_in_threadpool(dependant.call, **values)                                                                      │
                    │    163                                                                                                                                       │
                    │    164                                                                                                                                       │
                    │    165 def get_request_handler(                                                                                                              │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\starlette\concurrency.py:41 in run_in_threadpool                                │
                    │                                                                                                                                              │
                    │   38 │   if kwargs:  # pragma: no cover                                                                                                      │
                    │   39 │   │   # run_sync doesn't accept 'kwargs', so bind them in here                                                                        │
                    │   40 │   │   func = functools.partial(func, **kwargs)                                                                                        │
                    │ ❱ 41 │   return await anyio.to_thread.run_sync(func, *args)                                                                                  │
                    │   42                                                                                                                                         │
                    │   43                                                                                                                                         │
                    │   44 class _StopIteration(Exception):                                                                                                        │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\anyio\to_thread.py:31 in run_sync                                               │
                    │                                                                                                                                              │
                    │   28 │   :return: an awaitable that yields the return value of the function.                                                                 │
                    │   29 │                                                                                                                                       │
                    │   30 │   """                                                                                                                                 │
                    │ ❱ 31 │   return await get_asynclib().run_sync_in_worker_thread(                                                                              │
                    │   32 │   │   func, *args, cancellable=cancellable, limiter=limiter                                                                           │
                    │   33 │   )                                                                                                                                   │
                    │   34                                                                                                                                         │
                    │                                                                                                                                              │
                    │ C:\Users\user\AppData\Roaming\Python\Python310\site-packages\anyio\_backends\_asyncio.py:937 in run_sync_in_worker_thread                    │
                    │                                                                                                                                              │
                    │    934 │   │   │   context = copy_context()                                                                                                  │
                    │    935 │   │   │   context.run(sniffio.current_async_library_cvar.set, None)                                                                 │
                    │    936 │   │   │   worker.queue.put_nowait((context, func, args, future))                                                                    │
                    │ ❱  937 │   │   │   return await future                                                                                                       │
                    │    938                                                                                                                                       │
                    │    939                                                                                                                                       │
                    │    940 def run_sync_from_thread(                                                                                                             │
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
                    CancelledError
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f312' in position 0: character maps to <undefined>
Call stack:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\khoj.exe\__main__.py", line 7, in <module>
    sys.exit(run())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 72, in run
    start_server(app, host=args.host, port=args.port, socket=args.socket)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 140, in start_server
    logger.info("🌒 Stopping Khoj")
Message: '🌒 Stopping Khoj'
Arguments: ()
[13:53:33] INFO     🌒 Stopping Khoj                                                                                                                                     main.py:140
```

**Comment by Mahgozar** [comment]
after i ran it again it gave me the following error 
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f318' in position 0: character maps to <undefined>
Call stack:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\khoj.exe\__main__.py", line 7, in <module>
    sys.exit(run())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 64, in run
    logger.info("🌘 Starting Khoj")
Message: '🌘 Starting Khoj'
Arguments: ()
[13:57:02] INFO     🌘 Starting Khoj                                                                          main.py:64--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f48e' in position 0: character maps to <undefined>
Call stack:
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\khoj.exe\__main__.py", line 7, in <module>
    sys.exit(run())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 70, in run
    configure_server(args, required=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 49, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 112, in configure_search
    logger.info("💎 Setting up search for markdown notes")
Message: '💎 Setting up search for markdown notes'
Arguments: ()
           INFO     💎 Setting up search for markdown notes                                             configure.py:112
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 70, in run
    configure_server(args, required=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 49, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 114, in configure_search
    model.markdown_search = text_search.setup(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\search_type\text_search.py", line 180, in setup
    entries_with_indices = text_to_jsonl(config).process(previous_entries)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\processor\markdown\markdown_to_jsonl.py", line 59, in process
    jsonl_data = MarkdownToJsonl.convert_markdown_maps_to_jsonl(entries)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\processor\markdown\markdown_to_jsonl.py", line 136, in convert_markdown_maps_to_jsonl
    return "".join([f"{entry.to_json()}\n" for entry in entries])
MemoryError
```

**Comment by debanjum** [comment]
Thanks for sharing the more extensive error logs. The two main concerning things I can see are:

1. > UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f318' in position 0: character maps to <undefined>

   Not sure why (atleast) some folks are still hitting this issue. Quoting from my comment to [this issue](https://github.com/debanjum/khoj/issues/175#issuecomment-1449495705):
    > I'd fixed some file encoding related bugs in https://github.com/debanjum/khoj/issues/89. But seems like we still haven't cleared all of them up.
   
    > This is unexpected if you are using Obsidian. As based on [my earlier readings](https://forum.obsidian.md/t/better-handle-md-files-not-stored-in-utf8-format/13524/10) it seems like Obsidian stores all markdown files in your vault with utf8 encoding. So Khoj trying to read the same markdown files in your vault as utf-8 shouldn't ideally fail with the unicode decode error. 🤔

2. > return "".join([f"{entry.to_json()}\n" for entry in entries])
    > MemoryError

Let me get back to you on this in a bit after investigating this on my end?

Until then, another thing you can try is just delete the khoj directory at `C:\Users\user\.khoj`, restart the khoj backend and re-enable the khoj obsidian plugin. 

If it's just a (index) corruption issue then trying above solution may fix it for you. Otherwise hopefully my investigation uncovers the potential problem 🤞🏾

**Comment by Mahgozar** [comment]
> Thanks for sharing the more extensive error logs. The two main concerning things I can see are:
> 
>     1. > UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f318' in position 0: character maps to
>        
>        
>        Not sure why (atleast) some folks are still hitting this issue. Quoting from my comment to [this issue](https://github.com/debanjum/khoj/issues/175#issuecomment-1449495705):
>        > I'd fixed some file encoding related bugs in [UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2: invalid start byte for some org files #89](https://github.com/debanjum/khoj/issues/89). But seems like we still haven't cleared all of them up.
>        
>        
>        > This is unexpected if you are using Obsidian. As based on [my earlier readings](https://forum.obsidian.md/t/better-handle-md-files-not-stored-in-utf8-format/13524/10) it seems like Obsidian stores all markdown files in your vault with utf8 encoding. So Khoj trying to read the same markdown files in your vault as utf-8 shouldn't ideally fail with the unicode decode error. 🤔
> 
>     2. > return "".join([f"{entry.to_json()}\n" for entry in entries])
>        > MemoryError
> 
> 
> Let me get back to you on this in a bit after investigating this on my end?
> 
> Until then, another thing you can try is just delete the khoj directory at `C:\Users\user\.khoj`, restart the khoj backend and re-enable the khoj obsidian plugin.
> 
> If it's just a (index) corruption issue then trying above solution may fix it for you. Otherwise hopefully my investigation uncovers the potential problem 🤞🏾

I've tried deleting the directory and reinstalling khoj from the start but its the exact same issue all over

**Comment by debanjum** [comment]
Ok, some updates on the two issues that identified from your logs:
1. The smaller issue was the logger wasn't using utf-8 encoding. This should now be resolved in https://github.com/debanjum/khoj/commit/d90df966a9fd2e62250dbbc922210707b486c796
2. The MemoryError: This maybe an issue with your machine running out of RAM. This is interesting, if true, as it may provide a lower bound on memory requirements for Khoj
    - Can you share the RAM available on your machine?
    - If my hypothesis is true, when you start khoj you should see the RAM/Memory Usage spike in the Windows Task Manager until there is (almost?) no free memory available. After this khoj should fail with the MemoryError and memory should be freed up. Let me know if this is the behavior you see?

**Comment by Mahgozar** [comment]
i tested this on two of my machines both with 8 gigabytes of ram im gonna try it again with 16 gigabytes again today and update you on it

**Comment by Mahgozar** [comment]
ok so im testing it on the 16gb ram machine, its using around 4 gb of ram in the initial stages of indexing and 20% CPU which i think is enough to confirm your hypothesis
there is still no error i'll update if i got an error

**Comment by Mahgozar** [comment]
Ok another test it used up to 14 gigs of ram 😂😂😂 I have to note my obsidian vault is rather large

**Comment by debanjum** [comment]
I see, thanks for running the test on machines with different RAM configurations! Does that mean you can use khoj on your machine with 16 gigs of ram? Good to know that indexing was initially failing because for your vault khoj required more than 8Gb of RAM. 

If you don't mind, can you share how large your obsidian vault is (in terms of total files)?

> it would be great if I could use it on my other machines too

I haven't optimized Khoj for RAM usage yet, so there should be ways to drop the RAM usage down but that'll take me some time (1-2 months) to get to. Until then, some options to try are:
1. Given khoj should take max RAM only on first run when khoj indexes all your notes, you can try just copy the `~/.khoj/` directory from your 16Gb machine to your 8Gb machine and start khoj. You may need to update paths in `khoj.yml` and the name of the index files (ends with `.pt` and `.jsonl.gz`) under `~/.khoj/content/markdown` to path of your vault on the 8Gb machines. Subsequent (automatic) indexing runs should only index changes to your notes and not take as much RAM.
2. Call Khoj backend running on your 16Gb machine from your obsidian running on the 8Gb machine. You'll need to update the server URL in the khoj obsidian plugin settings to point to the 16Gb machine URL where khoj is running. See [Access Khoj on Mobile](https://github.com/debanjum/khoj#access-khoj-on-mobile) for example setup with [Tailscale](https://tailscale.com)

**Comment by Mahgozar** [comment]
> I see, thanks for running the test ona machines with different RAM configurations! Does that mean you can use khoj on your machine with 16 gigs of ram? Good to know that indexing was initially failing because for your vault khoj required more than 8Gb of RAM. 
> 
> If you don't mind, can you share how large your obsidian vault is (in terms of total files)?
> 
> > it would be great if I could use it on my other machines too
> 
> I haven't optimized Khoj for RAM usage yet, so there should be ways to drop the RAM usage down but that'll take me some time (1-2 months) to get to. Until then, some options to try are:
> 1. Given khoj should take max RAM only on first run when khoj indexes all your notes, you can try just copy the `~/.khoj/` directory from your 16Gb machine to your 8Gb machine and start khoj. You may need to update paths in `khoj.yml` and the name of the index files (ends with `.pt` and `.jsonl.gz`) under `~/.khoj/content/markdown` to path of your vault on the 8Gb machines. Subsequent (automatic) indexing runs should only index changes to your notes and not take as much RAM.
> 2. Call Khoj backend running on your 16Gb machine from your obsidian running on the 8Gb machine. You'll need to update the server URL in the khoj obsidian plugin settings to point to the 16Gb machine URL where khoj is running. See [Access Khoj on Mobile](https://github.com/debanjum/khoj#access-khoj-on-mobile) for example setup with [Tailscale](https://tailscale.com)

I'll try your suggestions for my other setups thank you for those 
And my vault has around 4300 notes and around it takes around 5gb of disk
