### ISSUE TITLE
Unable to start Khoj

### ISSUE THREAD

**Issue by jmhsimplicate** [khoj-ai/khoj#271]
Hi,

I've been trying to get Khoj running, but when following the instructions of installing and running Khoj, I run into the same error on different (Windows) machines. Please note that I have almost zero knowledge of Python or anything programming related.

This is the error I get on both machines:

PS C:\Users\WinUser> khoj
[09:44:28] INFO     🌘 Starting Khoj                                                                          main.py:64Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python311\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\khoj\main.py", line 76, in run
    main_window = MainWindow(args.config_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\khoj\interface\desktop\main_window.py", line 63, in __init__
    ) or self.get_default_config(search_type=search_type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python311\Lib\site-packages\khoj\interface\desktop\main_window.py", line 192, in get_default_config
    return config["content-type"][search_type]  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: <SearchType.All: 'all'>

**Comment by hgascon** [comment]
I have also get the same error in MacOS after installing the module with pip.

**Comment by sabaimran** [comment]
Hey @hgascon , @jmhsimplicate! Apologies for the bugs. We changed some default with search and our UI and missed testing this.

I fixed that issue [after the release](https://github.com/khoj-ai/khoj/commit/c7475628979795d85dc151e4ea24dd9c7ffbf99a#diff-58d9a7899a9a9eb782aa2b9971c1e6a9046bfe2c7726f17477636414525533da). 

Can you try running `pip install --upgrade --pre khoj-assistant` to get on the latest release and see if that resolves your issue?

To start Khoj, you can either run `khoj` or `khoj --gui`.

**Comment by jmhsimplicate** [comment]
Thank you for your reply!
I tried it on both machines, the VM with a clean Windows install seemed to work, it updated and I was able to run Khoj.
I now run into these messages when configuring:
Unable to reinitialize. Raise issue on Khoj Discord or Github
Unable to save configuration. Raise issue on Khoj Discord or Github.


With my other machine, where I also have Whisper and another AI Chat module running, I still get errors:

`Traceback (most recent call last):
  File "pydantic\main.py", line 522, in pydantic.main.BaseModel.parse_obj
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\site-packages\khoj\main.py", line 48, in run
    args = cli(state.cli_args)
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\site-packages\khoj\utils\cli.py", line 48, in cli
    args.config = parse_config_from_file(args.config_file)
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\site-packages\khoj\utils\yaml.py", line 47, in parse_config_from_file
    return parse_config_from_string(load_config_from_file(yaml_config_file))
  File "C:\Users\WinUser\AppData\Local\Programs\Python\Python39\lib\site-packages\khoj\utils\yaml.py", line 42, in parse_config_from_string
    return FullConfig.parse_obj(yaml_config)
  File "pydantic\main.py", line 525, in pydantic.main.BaseModel.parse_obj
pydantic.error_wrappers.ValidationError: 1 validation error for FullConfig
__root__
  FullConfig expected dict not NoneType (type=type_error)`

**Comment by debanjum** [comment]
Hi @jmhsimplicate, for the config issue, how are you trying to configure khoj? From Obsidian, the Web UI or Emacs? If you can share how your `khoj.yml` config file at `C:\Users\WinUser\.khoj\khoj.yml` looks, we can help debug why the configuration is erroring out.

Note: Make sure you censor/hide/remove your OpenAI API key etc when you share the khoj.yml config

**Comment by jmhsimplicate** [comment]
Hi! Thanks again for the reply! I have it working :) I think it was a mistake on my side. I didn't configure anything, just pressed "Configure". Now that I have it setup as an Obsidian Plugin, it's all working!

But this is on my VM that had nothing installed beore.

On my local machine, that is also running **OpenAI Whisper** and **Vicuna**, I still get the error I quoted above.

**Comment by debanjum** [comment]
Hey @jmhsimplicate 
Great to know you at least got it working on your VM with Obsidian!

Try the following:
1. Ensure you're on the latest khoj release (0.7.1) by running `pip install --upgrade khoj-assistant`
2. Delete your khoj folder at `C:\Users\WinUser\.khoj`
3. Restart khoj from your terminal (e.g by running `khoj` on terminal)
4. Restart Obsidian with the latest khoj Obsidian plugin installed

If that still results in the same error, maybe share how your `khoj.yml` config file looks and we can help debug why the configuration is erroring out

**Comment by debanjum** [comment]
Hey @jmhsimplicate, I'll close this issue to prevent stale issues piling up.
Please feel free to re-open this issue or start a [new discussion](https://github.com/khoj-ai/khoj/discussions/new?category=q-a) if you still can't get Khoj to work for you
