### ISSUE TITLE
Run Khoj with Multiple Instances, Vaults

### ISSUE THREAD

**Issue by Jawabiscuit** [khoj-ai/khoj#296]
I'm not sure if it's because I have 2 installations, but khoj is not starting for me anymore. First, I installed khoj in a python39 virtualenv on windows in the $LOCALAPPDATA/Obsidian install dir in a bash environment and it was working with Obsidian with a few errors here and there. I wanted to install a new instance in a vault directory using the same virtualenv method but in a powershell this time to see if I can reduce the warnings/errors related to file path (cannot find C: etc...). Now khoj server will not start and I get this EOFError. I only attempt to run one server at any given time.

As an aside, I'm curious as to how it's supposed to function on machines that have multiple vaults. I have different vaults for different purposes/interests.

Incidentally, I'm trying khoj out on a new vault I created using this template: https://github.com/Jawabiscuit/bhov-2023 which is forked from Bramses'. 

```bash
javrin@vrexton MINGW64 ~/AppData/Local/Obsidian
$ khoj --version
0.7.1
(venv_py3)
javrin@vrexton MINGW64 ~/AppData/Local/Obsidian
$ khoj
[12:21:53] INFO     🌘 Starting Khoj                                                                                       main.py:65
           INFO     💎 Setting up search for markdown notes                                                          configure.py:117
[12:21:54] ERROR    🚨 Failed to setup search                                                                        configure.py:171
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\main.py", line 73, in run
    configure_server(args, required=False)
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\configure.py", line 54, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\configure.py", line 172, in configure_search
    raise e
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\configure.py", line 119, in configure_search
    model.markdown_search = text_search.setup(
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 194, in setup
    corpus_embeddings = compute_embeddings(
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 70, in compute_embeddings
    corpus_embeddings = torch.load(get_absolute_path(embeddings_file), map_location=state.device)
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\jonas\AppData\Local\Obsidian\venv_py3\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

```powershell
Successfully installed khoj-assistant-0.7.2.dev46
(venv_py3) PS P:\obsidian\ai-notes> khoj
[14:31:58] INFO     🌘 Starting Khoj                                                                                       main.py:65
           INFO     💎 Setting up search for markdown notes                                                          configure.py:120
[14:31:59] ERROR    🚨 Failed to setup search                                                                        configure.py:186
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "P:\obsidian\ai-notes\venv_py3\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\main.py", line 72, in run
    configure_server(args, required=False)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 55, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 187, in configure_search
    raise e
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 122, in configure_search
    model.markdown_search = text_search.setup(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 199, in setup
    corpus_embeddings = compute_embeddings(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 70, in compute_embeddings
    corpus_embeddings = torch.load(get_absolute_path(embeddings_file), map_location=state.device)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by sabaimran** [comment]
Sorry about the setup issues @Jawabiscuit , and thanks for reporting.

Were either of these fresh installations? The stack trace itself seems to indicate that Khoj was trying to read the existing embeddings but was unable to find them.

I have two possible suggestions:
1. Can you try starting Khoj with `khoj --regenerate`?
2. If above doesn't work, can you delete your `.khoj` folder? I believe this should be at `C:\Users\<username>\.khoj\khoj.yml`.

**Comment by Jawabiscuit** [comment]
Perfect, `--regenerate` did what it was supposed to do I think, but then I encountered the directory doesn't exist error. And yes, one of the installations was a clean install so it seems that installing more than once to have access to more than one instance running non concurrently, my reasoning above, isn't supported for now, unless I'm missing something. Which is fine, I'm only figuring out how to use khoj most effectively with my setup.

So the second error...

```
[17:56:19] INFO     🌘 Starting Khoj                                                                                                                      main.py:65
           INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
[17:56:20] INFO     📩 Indexing 296 text entries. Creating index from scratch.                                                                     text_search.py:91
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:19<00:00,  1.91s/it]
[17:56:40] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "P:\obsidian\ai-notes\venv_py3\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\main.py", line 72, in run
    configure_server(args, required=False)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 55, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 187, in configure_search
    raise e
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 122, in configure_search
    model.markdown_search = text_search.setup(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 199, in setup
    corpus_embeddings = compute_embeddings(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 99, in compute_embeddings
    torch.save(corpus_embeddings, embeddings_file)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory P: does not exist.
(venv_py3) PS P:\obsidian\ai-notes> khoj --version
0.7.2.dev46
```

I then removed ~/.khoj

```
(venv_py3) PS P:\obsidian\ai-notes> khoj
[18:07:54] INFO     🌘 Starting Khoj                                                                                                                      main.py:65
           WARNING  Khoj is not configured.                                                                                                          configure.py:42
                    Configure it via http://localhost:8000/config, plugins or by editing C:\Users\jonas\.khoj\khoj.yml.
[18:07:55] INFO     🌖 Khoj is ready to use                                                                                                              main.py:145
           INFO     Started server process [26220]                                                                                                      server.py:75
           INFO     Waiting for application startup.                                                                                                        on.py:45
           INFO     Application startup complete.                                                                                                           on.py:59
           INFO     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

```
[18:11:56] INFO     📩 Saved computed text embeddings to C:\Users\jonas\.khoj\content\pdf\P__obsidian_ai-notes.pt                                 text_search.py:100
           INFO     📬 Search index updated via API                                                                                                       api.py:417
           INFO     📬 Processor reconfigured via API                                                                                                     api.py:426
           INFO     127.0.0.1:3584 - "GET /api/update?t=pdf HTTP/1.1" 200                                                                            h11_impl.py:431
[18:12:37] INFO     127.0.0.1:3633 - "GET /api/config/data HTTP/1.1" 200                                                                             h11_impl.py:431
           INFO     127.0.0.1:3633 - "GET /api/config/data/default HTTP/1.1" 200                                                                     h11_impl.py:431
           INFO     127.0.0.1:3633 - "GET /api/config/data HTTP/1.1" 200                                                                             h11_impl.py:431
           INFO     127.0.0.1:3633 - "POST /api/config/data HTTP/1.1" 200                                                                            h11_impl.py:431
           INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
[18:12:38] INFO     📬 Search index updated via API                                                                                                       api.py:417
           INFO     💬 Setting up conversation processor                                                                                            configure.py:203
           INFO     📬 Processor reconfigured via API                                                                                                     api.py:426
           INFO     127.0.0.1:3633 - "GET /api/update?t=markdown HTTP/1.1" 200                                                                       h11_impl.py:431
           INFO     🖨️ Setting up search for pdf                                                                                                     configure.py:132
[18:12:40] INFO     📬 Search index updated via API                                                                                                       api.py:417
           INFO     💬 Setting up conversation processor                                                                                            configure.py:203
           INFO     📬 Processor reconfigured via API                                                                                                     api.py:426
           INFO     127.0.0.1:3633 - "GET /api/update?t=pdf HTTP/1.1" 200                                                                            h11_impl.py:431
[18:12:42] INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
[18:12:43] INFO     📩 Indexing 383 text entries. Creating index from scratch.                                                                     text_search.py:91
Batches:  42%|█████████████████████████████████████████████████▏                                                                    | 5/12 [00:35<00:35,  5.04s/it]
```

Thanks.

**Comment by sabaimran** [comment]
Okay, cool. It looks like that worked for setting up one of your vaults at least! Strange errors to get along the process.

For the multi-vault setup, here's what you'd want to do. Note that this would do search/chat across all the vaults you add:
1. Update to the latest version of Khoj:
```bash
pip install --upgrade khoj-assistant
```
2. Open Obsidian and go to your Khoj settings. Set `Autoconfigure` to `False`.
3. Go to http://localhost:8000/config/content_type/markdown and manually add the file paths to your different Vault directories under `Folders`.
4. Click `Save` and then from the settings page, click `Configure`: http://localhost:8000/config.

**Comment by Jawabiscuit** [comment]
Ok, I was obviously successful in setting up one vault, so then I went to vault B and enabled the plugin there and set autoconfigure to False. I did this, for better or worse, before clicking Configure at http://localhost:8000/config to initialize both paths to vault A and B. At that point I get the same errors popping up in the console. I think the server had begun embedding the markdown before Configure had a chance to complete.

![opera_UaBUISgxiv](https://github.com/khoj-ai/khoj/assets/219464/955b7c22-1efa-42dc-9793-39e20eccc886)


```powershell
08:51:51] INFO     127.0.0.1:1957 - "GET /api/config/data HTTP/1.1" 200                                                                             h11_impl.py:431
           INFO     127.0.0.1:1957 - "GET /api/config/data/default HTTP/1.1" 200                                                                     h11_impl.py:431
           INFO     127.0.0.1:1957 - "GET /api/config/data HTTP/1.1" 200                                                                             h11_impl.py:431
[08:51:52] INFO     127.0.0.1:1957 - "POST /api/config/data HTTP/1.1" 200                                                                            h11_impl.py:431
Batches:  16%|██████████████████▋                                                                                                 | 32/198 [05:01<29:46, 10.76s/it][08:56:55] INFO     127.0.0.1:2043 - "GET /config HTTP/1.1" 200                                                                                      h11_impl.py:431
Batches: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 198/198 [10:55<00:00,  3.31s/it]
[09:02:46] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
           ERROR    Parent directory P: does not exist.                                                                                                   api.py:409
           INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
           INFO     127.0.0.1:1956 - "GET /api/update?t=markdown HTTP/1.1" 500                                                                       h11_impl.py:431
[09:02:49] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
           ERROR    Ran out of input                                                                                                                      api.py:409
           INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
           INFO     127.0.0.1:1961 - "GET /api/update?t=markdown HTTP/1.1" 500                                                                       h11_impl.py:431
[09:02:52] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
           ERROR    Ran out of input                                                                                                                      api.py:409
           INFO     127.0.0.1:2044 - "GET /api/update?&client=web&force=false HTTP/1.1" 500                                                          h11_impl.py:431
[09:50:13] INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
[09:50:20] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
Exception in thread Thread-123:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 1299, in run
    self.function(*self.args, **self.kwargs)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\main.py", line 157, in poll_task_scheduler
    schedule.run_pending()
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 76, in update_search_index
    state.model = configure_search(state.model, state.config, regenerate=False)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 187, in configure_search
    raise e
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\configure.py", line 122, in configure_search
    model.markdown_search = text_search.setup(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 199, in setup
    corpus_embeddings = compute_embeddings(
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\khoj\search_type\text_search.py", line 70, in compute_embeddings
    corpus_embeddings = torch.load(get_absolute_path(embeddings_file), map_location=state.device)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "P:\obsidian\ai-notes\venv_py3\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```

**Comment by sabaimran** [comment]
@Jawabiscuit , I think you need to set `Autoconfigure` to False *before* changing vaults. Unfortunately, the moment you install or open Obsidian with the Khoj plugin installed, it will update your settings.

Now that you have Autoconfigure set to false, can you try removing the `.khoj` directory again, and re-initializing your configuration with vaults A and B as directories?

1. Delete `.khoj` directory
2. Restart `khoj`
3. Update directories to point to your Vaults
4. Click `Configure`
5. Open Obsidian and see if you're able to use Khoj

I'm hoping this should work now that you've set your Obsidian-Khoj plugin configuration to not autoconfigure by default.

**Comment by Jawabiscuit** [comment]
I had a feeling that would be the case, thanks for confirming my suspicion. I followed your suggestion, but it still says Unsuccessful when I click Configure.

```powershell
(venv_py3) PS P:\obsidian\ai-notes> khoj
[19:47:26] INFO     🌘 Starting Khoj                                                                                                                      main.py:65
           WARNING  Khoj is not configured.                                                                                                          configure.py:42
                    Configure it via http://localhost:8000/config, plugins or by editing C:\Users\jonas\.khoj\khoj.yml.
           INFO     🌖 Khoj is ready to use                                                                                                              main.py:145
           INFO     Started server process [32256]                                                                                                      server.py:75
           INFO     Waiting for application startup.                                                                                                        on.py:45
           INFO     Application startup complete.                                                                                                           on.py:59
           INFO     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)                                                                    server.py:206
[19:48:13] INFO     127.0.0.1:5099 - "POST /api/config/data/content_type/markdown HTTP/1.1" 200                                                      h11_impl.py:431
[19:48:18] INFO     127.0.0.1:5099 - "GET /config HTTP/1.1" 200                                                                                      h11_impl.py:431
[19:48:19] INFO     127.0.0.1:5099 - "GET /assets/pico.min.css HTTP/1.1" 304                                                                         h11_impl.py:431
           INFO     127.0.0.1:5100 - "GET /assets/khoj.css HTTP/1.1" 304                                                                             h11_impl.py:431
           INFO     127.0.0.1:5099 - "GET /assets/icons/khoj-logo-sideways.svg HTTP/1.1" 304                                                         h11_impl.py:431
           INFO     127.0.0.1:5100 - "GET /assets/icons/github.svg HTTP/1.1" 304                                                                     h11_impl.py:431
           INFO     127.0.0.1:5099 - "GET /assets/icons/notion.svg HTTP/1.1" 304                                                                     h11_impl.py:431
           INFO     127.0.0.1:5100 - "GET /assets/icons/markdown.svg HTTP/1.1" 304                                                                   h11_impl.py:431
           INFO     127.0.0.1:5099 - "GET /assets/icons/confirm-icon.svg HTTP/1.1" 304                                                               h11_impl.py:431
           INFO     127.0.0.1:5100 - "GET /assets/icons/org.svg HTTP/1.1" 304                                                                        h11_impl.py:431
           INFO     127.0.0.1:5099 - "GET /assets/icons/pdf.svg HTTP/1.1" 304                                                                        h11_impl.py:431
           INFO     127.0.0.1:5106 - "GET /assets/icons/chat.svg HTTP/1.1" 304                                                                       h11_impl.py:431
           INFO     127.0.0.1:5106 - "GET /assets/icons/favicon-128x128.png HTTP/1.1" 200                                                            h11_impl.py:431
[19:48:22] INFO     💎 Setting up search for markdown notes                                                                                         configure.py:120
           INFO     🤖 Downloading sentence-transformers/multi-qa-MiniLM-L6-cos-v1 model from web                                                      helpers.py:80
[19:48:23] INFO     📩 Saved sentence-transformers/multi-qa-MiniLM-L6-cos-v1 model to disk                                                             helpers.py:83
           INFO     🤖 Downloading cross-encoder/ms-marco-MiniLM-L-6-v2 model from web                                                                 helpers.py:80
           INFO     📩 Saved cross-encoder/ms-marco-MiniLM-L-6-v2 model to disk                                                                        helpers.py:83
[19:48:32] ERROR    🚨 Failed to setup search                                                                                                       configure.py:186
           ERROR    Ran out of input                                                                                                                      api.py:409
           INFO     127.0.0.1:5106 - "GET /api/update?&client=web&force=false HTTP/1.1" 500                                                          h11_impl.py:431
[19:48:54] INFO     127.0.0.1:5107 - "GET /config/content_type/markdown HTTP/1.1" 200                                                                h11_impl.py:431
           INFO     127.0.0.1:5107 - "GET /assets/icons/khoj-logo-sideways.svg HTTP/1.1" 304                                                         h11_impl.py:431
           INFO     127.0.0.1:5108 - "GET /assets/icons/markdown.svg HTTP/1.1" 304
```

I cannot use search or chat inside Obsidian. It doesn't appear to attempt to start indexing on its own so I have to force it to update.

**Comment by sabaimran** [comment]
🤔 Would you say there's anything particularly special about your markdown files? Do you have markdown files present in all your vaults? Does it work on each vault independently, or does it always fail for each vault?

Can you try using the `Reinitialize` button on the configuration page?

Khoj is finding a file in the place where it expects to find your Markdown embeddings for some reason, but then that file is empty. I'm trying to understand why this might happen...I imagine it could be the case if you just have a series of empty markdown files, but I doubt that's the case here.

**Comment by sabaimran** [comment]
Are you still running multiple Khoj instances? If so, I think this would definitely be the cause if one instance is in the middle of writing to the file and the other is trying to read from it.

Can you try opening the embeddings file (by default at `P:Users/<username>/.khoj/content/markdown/markdown_embeddings.pt`) and tell me whether it's empty or not?

**Comment by sabaimran** [comment]
You should also make sure you disable autoconfigure on *both* Obsidian vaults.

**Comment by Jawabiscuit** [comment]
> You should also make sure you disable autoconfigure on both Obsidian vaults.

Autoconfigure has been disabled on both vaults

> Are you still running multiple Khoj instances?

I Have never run multiple instances concurrently, only installed khoj in different locations and tried using with different shells, since I run gitbash normally I tried powershell.

> Can you try opening the embeddings file

When I reproduce the issue there is no content directory

> anything particularly special about your markdown files?

Nothing particularly special, vault A is a clone of this [template](https://github.com/Jawabiscuit/bhov-2023) which has markdown files with content in them and vault B is an actual vault in use which indexes 5k entries, or I've tried cloning a second copy of A. I seem to have success with A but when I try and use another vault I run into issues.

---

Here's the workflow that's mostly working for me as of now, mostly b/c there seem to be multiple issues going on.

1. Stop `khoj` server
2. Clone template (which has the plugin installed but not enabled) to test-vault-a and test-vault-b
3. Add openai api key and disable auto-config in both vaults
4. Remove ~/.khoj if it exists
5. Start `khoj` server
6. Add openai api key and folders in khoj settings `P:/obsidian/test-vault-a` and `P:/obsidian/test-vault-b` (note forward slashes seem to make a difference)
7. Save
8. Configure

__test-vault-a__

Search seems to work mostly, I disabled dataview since it seems to mess with rendering in the search modal but there's other conflicts there I haven't addressed that aren't blocking search use.
![Search](https://github.com/khoj-ai/khoj/assets/219464/2790d03f-6faa-41b2-8d13-f88ae5c7334f)

Chat seems to function but during the first attempts it needs a bit of coaxing to properly augment the prompts it's sending to the LLM. It's functioning, which is all I care about at this point.
![Chat](https://github.com/khoj-ai/khoj/assets/219464/ddd8eea2-8b97-408d-af4d-a5229a1261db)

To reproduce issues, enable khoj plugin for test-vault-b *which has never been enabled*.

To avoid issues

1. Ctrl-c `khoj` in the terminal
2. Enable the plugin in test-vault-b
3. Paste openai api key and uncheck auto-configure
4. Start `khoj`

However, test-vault-b will not connect to the backend no matter if I uninstall/install the plugin. There are no errors on the backend so that is good.

![Disconnected from backend](https://github.com/khoj-ai/khoj/assets/219464/90bc7930-5047-43f4-bcc5-c08ef0b1d4db)

Only if I uninstall the plugin, install it again, and enable it with khoj running will the plugin connect to the server, but obviously this breaks usage as described above. Another side-effect of enabling the plugin which has auto-configure turned on is the folder paths obviously all the configuration gets blown away.

**Comment by Jawabiscuit** [comment]
> > Can you try opening the embeddings file

> When I reproduce the issue there is no content directory

I've also reproduced the errors and the .pt file is there with content.

![explorer_2zM1kir6US](https://github.com/khoj-ai/khoj/assets/219464/4108aac6-ff88-4bf8-b1d7-9900c1dc9a54)

**Comment by sabaimran** [comment]
Thanks for the additional screenshots, @Jawabiscuit. At least search is working, though it's a bit strange that the Chat question didn't pull in the relevant context. Do you think Search is giving you accurate results?

I was trying to reproduce your error yesterday and I also ran into the problem you highlighted, where the Khoj plugin in Obsidian would randomly disconnect after I'd disabled autoconfigure. I don't have a root cause yet, but it did work for me after quitting & restarting Obsidian once. I was eventually able to have it running in two different vaults with my single Khoj instance, though.

**Comment by debanjum** [comment]
With #549 Khoj server should be able to index multiple vaults across Obsidian vaults with Khoj plugin installed.
This is because of better client, server code separation. Clients now send the files to the server instead of updating the local file paths the server should pull from. This along with using a DB should provide better multi instance, multi-vault support.
