### ISSUE TITLE
PackageNotFoundError while running Khoj from precompiled `.deb`

### ISSUE THREAD

**Issue by ngirard** [khoj-ai/khoj#349]
Using the latest precompiled Debian package on Ubuntu 23.04.

Performing
```sh
sudo dpkg -i ./khoj_0.9.0_amd64.deb
/opt/Khoj
```
produces the following trace:
```
Traceback (most recent call last):
  File "transformers/utils/versions.py", line 102, in require_version
  File "importlib/metadata.py", line 569, in version
  File "importlib/metadata.py", line 542, in distribution
  File "importlib/metadata.py", line 196, in from_name
importlib.metadata.PackageNotFoundError: huggingface-hub

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "khoj/main.py", line 28, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "khoj/configure.py", line 21, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "khoj/search_type/image_search.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sentence_transformers/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sentence_transformers/datasets/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "sentence_transformers/SentenceTransformer.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "transformers/__init__.py", line 26, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "transformers/dependency_versions_check.py", line 57, in <module>
  File "transformers/utils/versions.py", line 117, in require_version_core
  File "transformers/utils/versions.py", line 104, in require_version
importlib.metadata.PackageNotFoundError: The 'huggingface-hub>=0.14.1,<1.0' distribution was not found and is required by this application. 
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
[4007254] Failed to execute script 'main' due to unhandled exception!
```

**Comment by sabaimran** [comment]
Hey @ngirard ! Thanks for raising this issue and trying the `.deb` package. I also ran into this problem and was working on a fix for it this past week.

I managed to fix the import issues in https://github.com/khoj-ai/khoj/pull/343, but we haven't done a new release with new images yet. Hopefully we should have that done in the next day or so!

**Comment by ngirard** [comment]
Hey @sabaimran, great !

Thanks for involving yourself into such a nice project, and congrats for the funding !

**Comment by debanjum** [comment]
@ngirard, I'll mark this issue as completed, as this error in installing the debian package should be resolved.
Feel free to re-open if you're still hitting the same problem with the khoj debian package from the latest release
