### ISSUE TITLE
ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers'

### ISSUE THREAD

**Issue by JakeStevenson** [khoj-ai/khoj#404]
MacOS Ventura, M2 chip with 32G Ram.

I've updated to the latest Khoj-Assistant using `pip install --upgrade khoj-assistant`, and cleaned out my ~/.khoj folder to start fresh.

When running, it fails with:
```
[08:31:58] INFO     🌘 Starting Khoj                                                                                                           main.py:66
           WARNING  🚨 Khoj is not configured.                                                                                            configure.py:46
                    Configure it via http://localhost:42110/config, plugins or by editing /Users/jakes/.khoj/khoj.yml.
Traceback (most recent call last):
  File "/opt/homebrew/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/main.py", line 74, in run
    configure_routes(app)
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/configure.py", line 98, in configure_routes
    from khoj.routers.api import api
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/routers/api.py", line 39, in <module>
    from khoj.routers.helpers import perform_chat_checks, generate_chat_response, update_telemetry_state
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/routers/helpers.py", line 10, in <module>
    from khoj.processor.conversation.openai.gpt import converse
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/processor/conversation/openai/gpt.py", line 12, in <module>
    from khoj.processor.conversation.openai.utils import (
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/processor/conversation/openai/utils.py", line 22, in <module>
    from khoj.processor.conversation.utils import ThreadedGenerator
  File "/opt/homebrew/lib/python3.9/site-packages/khoj/processor/conversation/utils.py", line 10, in <module>
    from transformers import LlamaTokenizerFast
ImportError: cannot import name 'LlamaTokenizerFast' from 'transformers' (/Users/jakes/Projects/gpt4all/transformers/src/transformers/__init__.py)
```

**Comment by sabaimran** [comment]
Interesting! Thanks for raising this. We need to specify a minimum version of the `transformer` library. It looks like you had an older one hanging around and it defaulted to that one. I'll create a quick fix for this.

**Comment by sabaimran** [comment]
@JakeStevenson , could you try running `pip install --pre khoj-assistant` and see if this fixes your issue?

**Comment by JakeStevenson** [comment]
Sorry, I'll admit my knowledge of managing python dependencies is pretty rudimentary.  I've been trying to use conda to try and ensure an environment makes sense.

I uninstalled khoj-assistant using pip.  
I created a new conda environment for khoj -- `conda create -n khoj; conda activate khoj`
I ran `pip install --pre khoj-assistant`

Now when I run khoj, I'm getting a new error:
```
Traceback (most recent call last):
  File "/Users/jakes/anaconda3/bin/khoj", line 5, in <module>
    from khoj.main import run
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/khoj/main.py", line 28, in <module>
    from khoj.configure import configure_routes, initialize_server
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/khoj/configure.py", line 20, in <module>
    from khoj.search_type import image_search, text_search
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/khoj/search_type/image_search.py", line 11, in <module>
    from sentence_transformers import SentenceTransformer, util
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 11, in <module>
    import transformers
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/Users/jakes/anaconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

Sorry if I'm adding noise.  If I figure out anything further I'll update here.

**Comment by JakeStevenson** [comment]
I completely reset my pip packages and managed to create a truly fresh environment in conda, and now it is working with `pip install --pre khoj-assistant`.  Thank you!

**Comment by debanjum** [comment]
That's great to know! Can you share what steps you took to reset your pip packages and setup a fresh conda environment? This may help others trying to setup khoj with conda

> Sorry, I'll admit my knowledge of managing python dependencies is pretty rudimentary. I've been trying to use conda to try and ensure an environment makes sense.

It's not you, python dependency management is messy for everyone 😅
