### ISSUE TITLE
ValueError: time data '2023-06-21 mer 10:45' does not match format '%Y-%m-%d %a %H:%M'

### ISSUE THREAD

**Issue by bbigras** [khoj-ai/khoj#419]
Maybe because my locale is fr_CA.

```yaml
content-type:
  org:
    compressed-jsonl: ~/.khoj/content/org/org.jsonl.gz
    embeddings-file: ~/.khoj/content/org/org_embeddings.pt
    index_heading_entries: false
    input-files: null
    input-filter: ["~/dev/org-mode/**/*.org"]
processor:
  conversation:
    conversation-logfile: ~/.khoj/processor/conversation/conversation_logs.json
    openai-api-key: <redacted>
search-type:
  asymmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/multi-qa-MiniLM-L6-cos-v1
    model_directory: ~/.khoj/search/asymmetric/
  image:
    encoder: sentence-transformers/clip-ViT-B-32
    model_directory: ~/.khoj/search/image/
  symmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/all-MiniLM-L6-v2
    model_directory: ~/.khoj/search/symmetric/
```

```
❯ khoj --no-gui
Traceback (most recent call last):
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/bin/..khoj-wrapped-wrapped", line 9, in <module>
    sys.exit(run())
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/main.py", line 80, in run
    configure_server(args, required=False)
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/configure.py", line 44, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/configure.py", line 60, in configure_search
    model.orgmode_search = text_search.setup(
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/search_type/text_search.py", line 170, in setup
    entries_with_indices = text_to_jsonl(config).process(previous_entries)
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/processor/org_mode/org_to_jsonl.py", line 41, in process
    entry_nodes, file_to_entries = self.extract_org_entries(org_files)
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/processor/org_mode/org_to_jsonl.py", line 99, in extract_org_entries
    org_file_entries = orgnode.makelist(str(org_file))
  File "/nix/store/dhw5jlrkdy2ggb6rgpf4q6xr3qg2am3m-khoj-0.3.0/lib/python3.10/site-packages/khoj/processor/org_mode/orgnode.py", line 159, in makelist
    clocked_in = datetime.datetime.strptime(clocked_re.group(1), "%Y-%m-%d %a %H:%M")
  File "/nix/store/9c03r86hcdn43dm3hsgjirifvyzfkhwh-python3-3.10.12/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/nix/store/9c03r86hcdn43dm3hsgjirifvyzfkhwh-python3-3.10.12/lib/python3.10/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-06-21 mer 10:45' does not match format '%Y-%m-%d %a %H:%M'
```

``` 
❯ khoj --version
0.3.0
```

**Comment by bbigras** [comment]
Note that I don't have this error when I run `khoj` without  `--no-gui`

**Comment by sabaimran** [comment]
@bbigras we deprecated the `--no-gui` arg a while ago 🤔 . Now, the default behavior is to rung without the gui. If you want to upgrade, the command is `pip install --upgrade khoj-assistant`.

That's definitely some interesting behavior. I can't right now think of a reason why it would work with the gui, but not without it.

1. Would you mind upgrading and seeing if the issue persists?
2. Could you share a small sample `org` file to help me reproduce the error?

**Comment by bbigras** [comment]
Oh my bad. I should have realized that I wasn't up-to-date.

I just tested with docker (master) and I get:

```
khoj-server-1  |                     ValueError: time data '2023-06-21 mer 10:45'
khoj-server-1  |                     does not match format '%Y-%m-%d %a %H:%M'
```

with this file:

```org
* test
:LOGBOOK:
CLOCK: [2023-06-21 mer 10:45]--[2023-06-21 mer 11:20] =>  0:35
:END:
```

**Comment by sabaimran** [comment]
@bbigras , I am able to reproduce the error, and it seems that it's dependent on localization of the code in python. I'll need a little more help from you to root cause it. Could you provide a little more detail?

1. Are you able to run `khoj` inside of a terminal? And does the issue reproduce consistently there?
2. Inside of your docker container, could you try setting the default locale to `fr_ca`? According to [this post](https://askubuntu.com/questions/89976/how-do-i-change-the-default-locale-in-ubuntu-server), I think the steps are the following:
```bash
sudo docker exec -it <khoj docker container id> bash
# Output current locale. Verify that it's en_us or some equivalent. If it's already fr_ca, no need to proceed.
locale
sudo locale-gen fr_CA
sudo locale-gen fr_CA.UTF-8
```

**Comment by bbigras** [comment]
It seems to work. Now I only have some `CUDA error: no kernel image is available for execution on the device` error. Not sure if it's normal or if I should open another issue.

**Comment by debanjum** [comment]
@bbigras good to know that this is resolved. It'd be great if you can open a separate issue for the CUDA error

**Comment by bbigras** [comment]
Will do, thanks for the quick fix!
