### ISSUE TITLE
django.db.utils.OperationalError

### ISSUE THREAD

**Issue by Zacharia2** [khoj-ai/khoj#600]
步骤：
1. 安装postgresql-16.1-1-windows-x64.exe，全部默认选项，并设置superman密码为0000。
2. createdb -U postgres khoj --password，然后输入密码0000
3. python -m pip install khoj-assistant，安装无报错，安装成功。
4. 执行下面的命令
5. $env:KHOJ_ADMIN_EMAIL="<my-email>"，这是我的email。
6. $env:KHOJ_ADMIN_PASSWORD="0000"
7. khoj --anonymous-mode 
8. 报错

postgresql的stack builder没有执行

---

Steps:
1. Install postgresql-16.1-1-windows-x64.exe with all default options and set superman password to 0000.
2. createdb -U postgres khoj --password and enter password 0000
3. python -m pip install khoj-assistant, install without error, install successfully.
4. Execute the following command
5. $env:KHOJ_ADMIN_EMAIL="<my-email>", this is my email.
6. $env:KHOJ_ADMIN_PASSWORD="0000"
7. khoj --anonymous-mode 
8. error

postgresql stack builder not executing

**Comment by Zacharia2** [comment]
步骤：
1. 安装postgresql-16.1-1-windows-x64.exe，全部默认选项，并设置superman密码为0000。
2. createdb -U postgres khoj --password，然后输入密码0000
3. python -m pip install khoj-assistant，安装无报错，安装成功。
4. $env:KHOJ_ADMIN_EMAIL="<my-email>"
5. $env:KHOJ_ADMIN_PASSWORD="0000"
6. khoj --anonymous-mode 
7. 报错

**Comment by Zacharia2** [comment]
```py
Traceback (most recent call last):
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\postgresql\base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Software\Scoop\apps\miniconda3\current\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Software\Scoop\apps\miniconda3\current\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Software\Scoop\apps\miniconda3\current\Scripts\khoj.exe\__main__.py", line 4, in <module>
    from khoj.main import run
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\khoj\main.py", line 40, in <module>
    call_command("migrate", "--noinput")
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\core\management\__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\core\management\base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\core\management\base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\core\management\commands\migrate.py", line 117, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\migrations\loader.py", line 58, in __init__
    self.build_graph()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\migrations\loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\migrations\recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\migrations\recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
r
    return self._cursor()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 306, in _cursor
    self.ensure_connection()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 288, in ensur    with self.wrap_database_errors:
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\django\db\backends\postgresql\base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "D:\Software\Scoop\apps\miniconda3\current\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError
```

**Comment by Zacharia2** [comment]
Maybe I should try docker or Linux.
