### ISSUE TITLE
Non fatal issue with Obsidian search

### ISSUE THREAD

**Issue by edbock** [khoj-ai/khoj#614]
I finally got up and running with the Obsidian plug-in. The incremental search is a dream come true! In fact, it's so good I couldn't have even imagined it would be an option so soon.

Since I've been troubleshooting other issues, I had my developer console tab open and noticed that each time I type, the following happens:

6plugin:dataview:20279 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'lastIndexOf')
    at isDataviewDisabled (plugin:dataview:20279:39)
    at eval (plugin:dataview:20644:60)
    at t.render (app.js:1:1276744)
    at t.renderMarkdown (app.js:1:1276059)
    at KhojSearchModal.renderSuggestion (plugin:khoj:4656:39)
    at e.setSuggestions (app.js:1:1530153)
    at i (app.js:1:1532515)
    at KhojSearchModal.<anonymous> (app.js:1:1532699)
    at app.js:1:237258
    at Object.next (app.js:1:237363)

I know this isn't a priority, but hopefully this is an easy issue for you to fix.

**Comment by debanjum** [comment]
Thanks for raising this issue. It was caused by the same bug that was causing problems for #606. It affected folks using Khoj from Obsidian with the dataview plugin installed. It's been fixed in #619. So should be resolved in next release of Khoj later today
