### ISSUE TITLE
ImportError: libGL.so.1

### ISSUE THREAD

**Issue by lamasseriadipolverara** [khoj-ai/khoj#846]
## Describe the bug
Updating khoji, can't start because of this problem:
Traceback (most recent call last):

  File "/app/src/khoj/main.py", line 93, in <module>

    from khoj.configure import configure_routes, initialize_server, configure_middleware

  File "/app/src/khoj/configure.py", line 40, in <module>

    from khoj.routers.indexer import configure_content, configure_search

  File "/app/src/khoj/routers/indexer.py", line 12, in <module>

    from khoj.processor.content.images.image_to_entries import ImageToEntries

  File "/app/src/khoj/processor/content/images/image_to_entries.py", line 7, in <module>

    from rapidocr_onnxruntime import RapidOCR

  File "/usr/local/lib/python3.10/dist-packages/rapidocr_onnxruntime/__init__.py", line 4, in <module>

    from .main import RapidOCR

  File "/usr/local/lib/python3.10/dist-packages/rapidocr_onnxruntime/main.py", line 8, in <module>

    import cv2

  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>

    bootstrap()

  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap

    native_module = importlib.import_module("cv2")

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

ImportError: libGL.so.1: cannot open shared object file: No such file or directory

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [x ] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [x] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [x] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:

**Comment by debanjum** [comment]
Hey @lamasseriadipolverara thanks for raising an issue for this. It was fixed in [this PR](https://github.com/khoj-ai/khoj/pull/842). You can build from source, as mentioned in https://github.com/khoj-ai/khoj/issues/848#issuecomment-2232410117 or use the [pre](https://github.com/khoj-ai/khoj/pkgs/container/khoj/242318022?tag=pre) tagged Khoj docker image.

The `latest` tagged docker images tracks the latest Khoj release. The fix was merged after the previous release. We should have a new release out in a few days as well, in case you want to wait.

**Comment by debanjum** [comment]
Closing this issue as it should be fixed now in the latest release (0.17.0)
